version: '3'

services:
  nginx:
    image: nginx:1.27.1
    container_name: nginx
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "80:80"
    volumes:
      # 证书映射
      - ./data/nginx/cert:/etc/nginx/cert
      # 配置文件映射
      - ./data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      # 页面目录
      - ./data/nginx/html:/usr/share/nginx/html
      # 日志目录
      - ./data/nginx/log:/var/log/nginx
    privileged: true
    networks:
      docker_net:
        ipv4_address: 177.177.177.120

networks:
  docker_net:
    external: true