server:
  port: 38078
spring:
  application:
    name: spring-boot-admin
  security:
    user:
      name: admin
      password: admin123456
  boot:
    admin:
      context-path: /spring-boot-admin
  thymeleaf:
    check-template-location: false